# Generated by Django 5.2.6 on 2025-09-14 20:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningrecord',
            options={'ordering': ['-date'], 'verbose_name': '学習記録', 'verbose_name_plural': '学習記録'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '学習テーマ', 'verbose_name_plural': '学習テーマ'},
        ),
        migrations.RenameField(
            model_name='learningrecord',
            old_name='description',
            new_name='memo',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='actual_hours',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='planned_hours',
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='planned_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='records.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
